name: "Update sam templates on pushes to the main branch"

on:
  push:
    branches:
      - master

jobs:
  buildaccount:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update SAM Template
        uses: ascending-llc/actions/sam@main
        with:
          python_v: '3.9'
          location: ./cft/sam/account_factory
          role_to_assume: arn:aws:iam::595312265488:role/GitHubSAMAssumeRole