name: "Update sam templates on pushes to the main branch"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Echo Branch Name
        shell: bash
        run: echo ${{ github.ref_name }}